"""Run HEXACO-60 questionnaire with a local HuggingFace model playing personas.

For each persona prompt (generated by ``generate_persona_prompts.py``), the
model answers all 60 HEXACO items.  Answers are repeated *answer_samples*
times and averaged to produce a single 1–5 integer per item.

Output:  ``questionnaire_answers.jsonl``  with one record per
(persona_id, prompt_idx, question_id):

    {"persona_id": 0, "prompt_idx": 0, "question_id": 1, "score": 3, ...}

This format is consumed directly by ``score_questionnaire.py``.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import random
import re
import sys
from typing import Dict, List, Optional, Tuple

import torch

ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from utils.model_loader import load_model_and_tokenizer, normalize_model_paths
from utils.chat_compat import adapt_messages


# ---------------------------------------------------------------------------
# Config helpers (same pattern as other pipeline scripts)
# ---------------------------------------------------------------------------
def load_cfg(path: pathlib.Path) -> Dict:
    return json.loads(path.read_text(encoding="utf-8"))


def apply_output_suffix(cfg: Dict) -> Dict:
    suffix = str(cfg.get("output_suffix", "")).strip()
    if not suffix:
        return cfg
    base = str(cfg.get("output_dir", "output"))
    if not base.endswith(f"_{suffix}") and not base.endswith(f"/{suffix}"):
        base = f"{base}_{suffix}"
    cfg["output_dir"] = base
    for key in ("prompts_file", "embedding_cache", "ae_checkpoint"):
        p = cfg.get(key)
        if isinstance(p, str) and p.startswith("output/"):
            cfg[key] = p.replace("output/", f"{base}/", 1)
    return cfg


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
def load_persona_prompts(path: pathlib.Path) -> List[Dict]:
    """Load persona_prompts.jsonl → list of {id, persona, prompts:[str×3]}."""
    records = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def load_questions(path: pathlib.Path) -> List[Dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return data["items"]


# ---------------------------------------------------------------------------
# Answer parsing
# ---------------------------------------------------------------------------
_NUM_RE = re.compile(r"([1-5])")

_WORD_MAP = {
    "strongly disagree": 1,
    "very strongly disagree": 1,
    "disagree": 2,
    "neither agree nor disagree": 3,
    "neutral": 3,
    "neither": 3,
    "agree": 4,
    "strongly agree": 5,
    "completely agree": 5,
}


def parse_answer(text: str) -> Optional[int]:
    """Extract a 1–5 integer from the model output."""
    text = text.strip()
    # Try textual English labels before falling back to a numeric answer.
    for word, val in _WORD_MAP.items():
        if word in text:
            return val
    m = _NUM_RE.search(text)
    if m:
        return int(m.group(1))
    return None


# ---------------------------------------------------------------------------
# Batched questionnaire generation
# ---------------------------------------------------------------------------
def build_chat_messages(
    persona_prompt: str,
    question_text: str,
) -> List[Dict[str, str]]:
    return [
        {
            "role": "system",
            "content": f"Answer the questionnaire strictly according to the following persona specification:\n{persona_prompt}",
        },
        {
            "role": "user",
            "content": (
                "Answer the following item with one number from 1 to 5 "
                "(1=strongly disagree, 2=disagree, 3=neither agree nor disagree, "
                "4=agree, 5=strongly agree). Output only the number.\n"
                f"{question_text}"
            ),
        },
    ]


def run_batched_questionnaire(
    model,
    tokenizer,
    persona_prompts: List[Dict],
    questions: List[Dict],
    cfg: Dict,
    output_path: pathlib.Path,
) -> None:
    """Run the full questionnaire with batched generation."""
    device = next(model.parameters()).device
    n_prompts = len(persona_prompts)
    n_questions = len(questions)
    n_samples = int(cfg.get("answer_samples", 3))
    max_new_tokens = int(cfg.get("answer_max_new_tokens", 3))
    temperature = float(cfg.get("answer_temperature", 0.9))
    top_p = float(cfg.get("answer_top_p", 0.93))
    do_sample = bool(cfg.get("answer_do_sample", True))
    batch_size = int(cfg.get("questionnaire_batch_size", 32))

    # Flatten: (persona_id, prompt_idx, question_id, question_text, persona_prompt)
    tasks: List[Tuple[int, int, int, str, str]] = []
    for rec in persona_prompts:
        pid = int(rec["id"])
        for pidx, p_text in enumerate(rec["prompts"]):
            for q in questions:
                tasks.append((pid, pidx, int(q["id"]), q["text"], p_text))

    total = len(tasks) * n_samples
    print(f"questionnaire: {len(tasks)} (persona,question) pairs × {n_samples} samples = {total} generations")
    print(f"  batch_size={batch_size}, max_new_tokens={max_new_tokens}, temperature={temperature}")

    # Left-pad for batched generation
    tokenizer.padding_side = "left"
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    # Collect raw answers: {(pid, pidx, qid): [sample_scores]}
    raw_answers: Dict[Tuple[int, int, int], List[int]] = {}

    model.eval()
    done = 0
    with torch.no_grad():
        for sample_i in range(n_samples):
            rng = random.Random(42 + sample_i)
            order = list(range(len(tasks)))
            rng.shuffle(order)

            for batch_start in range(0, len(order), batch_size):
                batch_indices = order[batch_start : batch_start + batch_size]
                batch_tasks = [tasks[i] for i in batch_indices]

                # Build chat messages for each task
                all_messages = [
                    adapt_messages(tokenizer, build_chat_messages(t[4], t[3])) for t in batch_tasks
                ]

                # Apply chat template
                # Qwen3 reasoning models need enable_thinking=False to avoid
                # generating <think>...</think> blocks that consume the limited
                # max_new_tokens budget. Detect Qwen3 via tokenizer config.
                _ct_kwargs = {"tokenize": False, "add_generation_prompt": True}
                _chat_template = getattr(tokenizer, "chat_template", None) or ""
                _tok_config = getattr(tokenizer, "chat_template", "") or ""
                # Robust check: Qwen3 templates support enable_thinking kwarg
                if "enable_thinking" in _chat_template:
                    _ct_kwargs["enable_thinking"] = False
                texts = [
                    tokenizer.apply_chat_template(msgs, **_ct_kwargs)
                    for msgs in all_messages
                ]

                # Tokenize with padding
                enc = tokenizer(
                    texts,
                    return_tensors="pt",
                    padding=True,
                    truncation=True,
                    max_length=int(cfg.get("max_seq_len", 512)),
                    add_special_tokens=False,
                )
                enc = {k: v.to(device) for k, v in enc.items()}

                gen_kwargs = dict(
                    **enc,
                    max_new_tokens=max_new_tokens,
                    do_sample=do_sample,
                    temperature=temperature if do_sample else 1.0,
                    top_p=top_p if do_sample else 1.0,
                    pad_token_id=tokenizer.pad_token_id,
                )

                outputs = model.generate(**gen_kwargs)
                # Decode only the newly generated tokens
                input_len = enc["input_ids"].shape[1]
                gen_tokens = outputs[:, input_len:]
                decoded = tokenizer.batch_decode(gen_tokens, skip_special_tokens=True)

                for task, text in zip(batch_tasks, decoded):
                    pid, pidx, qid, _, _ = task
                    score = parse_answer(text)
                    if score is None:
                        score = 3  # neutral fallback
                    key = (pid, pidx, qid)
                    raw_answers.setdefault(key, []).append(score)

                done += len(batch_tasks)
                if done % 500 == 0 or done >= total:
                    pct = done / total * 100
                    print(f"  progress: {done}/{total} ({pct:.1f}%)")

    # Aggregate and write
    output_path.parent.mkdir(parents=True, exist_ok=True)
    agg_mode = str(cfg.get("answer_agg", "mean"))
    n_written = 0
    with output_path.open("w", encoding="utf-8") as f:
        for (pid, pidx, qid), scores in sorted(raw_answers.items()):
            if agg_mode == "mean":
                avg = sum(scores) / len(scores)
                score = int(round(avg))
                score = max(1, min(5, score))
            elif agg_mode == "median":
                scores_sorted = sorted(scores)
                mid = len(scores_sorted) // 2
                score = scores_sorted[mid]
            else:
                score = scores[0]

            record = {
                "persona_id": pid,
                "prompt_idx": pidx,
                "question_id": qid,
                "score": score,
                "raw_scores": scores,
            }
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
            n_written += 1

    print(f"saved {n_written} answers to {output_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main(cfg_path: str | None = None):
    if cfg_path:
        cfg_path = pathlib.Path(cfg_path)
    else:
        default_cfg = pathlib.Path("config/ae_deepseek-r1-distill-qwen-7b.json")
        if not default_cfg.exists():
            default_cfg = pathlib.Path("config/ae.json")
        cfg_path = default_cfg

    cfg = apply_output_suffix(load_cfg(cfg_path))
    cfg = normalize_model_paths(cfg)
    torch.manual_seed(int(cfg.get("seed", 42)))

    output_dir = pathlib.Path(cfg.get("output_dir", "output"))
    prompts_file = pathlib.Path(cfg.get("prompts_file", str(output_dir / "persona_prompts.jsonl")))
    questions_file = pathlib.Path("data/questions/hexaco_60_en.json")
    out_path = output_dir / "questionnaire_answers.jsonl"

    if not prompts_file.exists():
        raise FileNotFoundError(
            f"persona prompts not found: {prompts_file}. "
            "Run generate_persona_prompts.py first."
        )

    persona_prompts = load_persona_prompts(prompts_file)
    questions = load_questions(questions_file)
    print(f"loaded {len(persona_prompts)} personas × {len(questions)} questions")

    model, tokenizer = load_model_and_tokenizer(cfg)
    run_batched_questionnaire(model, tokenizer, persona_prompts, questions, cfg, out_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run HEXACO questionnaire with local LLM")
    parser.add_argument("--config", type=str, default=None, help="path to AE config json")
    args = parser.parse_args()
    main(cfg_path=args.config)
